defaults: &defaults
  app_name: user-login-facebook-api
  default_url_options:
    host: localhost
    port: 3000
  asset_host: http://localhost:3000
  facebook:
    app_id: 976040333178618
    app_secret: 68ef68bfa024728a29e8dd82a276c3fe

development:
  <<: *defaults  